import { $ } from "bun";
import { mkdir, readdir, rm } from "node:fs/promises";
import { basename, join } from "node:path";

export type PatchEntry = {
  name: string;
  dir: string;
  patchFiles: string[];
  docPath: string;
  verificationPath: string;
};

export async function listPatchEntries(
  patchDir: string,
): Promise<PatchEntry[]> {
  const names = await readdir(patchDir, { withFileTypes: true }).catch(
    () => [],
  );

  const rootPatchFiles = names
    .filter((entry) => entry.isFile() && entry.name.endsWith(".patch"))
    .map((entry) => join(patchDir, entry.name))
    .sort();

  const entries: PatchEntry[] = [];

  if (rootPatchFiles.length > 0) {
    entries.push({
      name: "root",
      dir: patchDir,
      patchFiles: rootPatchFiles,
      docPath: join(patchDir, "patch.md"),
      verificationPath: join(patchDir, "verification.sh"),
    });
  }

  const patchDirs = names
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(patchDir, entry.name))
    .sort();

  for (const dir of patchDirs) {
    const files = await readdir(dir, { withFileTypes: true });
    const patchFiles = files
      .filter((entry) => entry.isFile() && entry.name.endsWith(".patch"))
      .map((entry) => join(dir, entry.name))
      .sort();

    if (patchFiles.length === 0) {
      continue;
    }

    entries.push({
      name: basename(dir),
      dir,
      patchFiles,
      docPath: join(dir, "patch.md"),
      verificationPath: join(dir, "verification.sh"),
    });
  }

  return entries;
}

export async function applyPatches(options: {
  targetDir: string;
  patchDir: string;
}) {
  const entries = await listPatchEntries(options.patchDir);

  for (const entry of entries) {
    for (const patchFile of entry.patchFiles) {
      await $`git apply ${patchFile}`.cwd(options.targetDir);
    }
  }

  return entries;
}

export async function regenerateSinglePatch(options: {
  targetDir: string;
  patchDir: string;
}) {
  await removePatchFiles(options.patchDir);

  const patchOneDir = join(options.patchDir, "patch_1");
  await mkdir(patchOneDir, { recursive: true });

  const diff = await $`git diff --binary`.cwd(options.targetDir).text();
  const patchPath = join(patchOneDir, "patch.patch");
  await Bun.write(patchPath, diff);

  const docPath = join(patchOneDir, "patch.md");
  const existingDoc = await Bun.file(docPath).exists();

  if (!existingDoc) {
    await Bun.write(
      docPath,
      [
        "# patch_1",
        "",
        "This patch was regenerated by PatchSync after an ACPX repair.",
        "",
      ].join("\n"),
    );
  }
}

async function removePatchFiles(patchDir: string) {
  const entries = await readdir(patchDir, { withFileTypes: true }).catch(
    () => [],
  );

  for (const entry of entries) {
    const path = join(patchDir, entry.name);

    if (entry.isFile() && entry.name.endsWith(".patch")) {
      await rm(path, { force: true });
    }

    if (!entry.isDirectory()) {
      continue;
    }

    const files = await readdir(path, { withFileTypes: true });
    for (const file of files) {
      if (file.isFile() && file.name.endsWith(".patch")) {
        await rm(join(path, file.name), { force: true });
      }
    }
  }
}
